package com.sky.ddt.dao.generate;

import com.sky.ddt.entity.LabelPrint;
import com.sky.ddt.entity.LabelPrintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LabelPrintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print
     *
     * @mbg.generated
     */
    long countByExample(LabelPrintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print
     *
     * @mbg.generated
     */
    int deleteByExample(LabelPrintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print
     *
     * @mbg.generated
     */
    int insert(LabelPrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print
     *
     * @mbg.generated
     */
    int insertSelective(LabelPrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print
     *
     * @mbg.generated
     */
    List<LabelPrint> selectByExample(LabelPrintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print
     *
     * @mbg.generated
     */
    LabelPrint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LabelPrint record, @Param("example") LabelPrintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LabelPrint record, @Param("example") LabelPrintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LabelPrint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LabelPrint record);
}