package com.sky.ddt.dao.generate;

import com.sky.ddt.entity.LabelPrintShopSku;
import com.sky.ddt.entity.LabelPrintShopSkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LabelPrintShopSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print_shop_sku
     *
     * @mbg.generated
     */
    long countByExample(LabelPrintShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print_shop_sku
     *
     * @mbg.generated
     */
    int deleteByExample(LabelPrintShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print_shop_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print_shop_sku
     *
     * @mbg.generated
     */
    int insert(LabelPrintShopSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print_shop_sku
     *
     * @mbg.generated
     */
    int insertSelective(LabelPrintShopSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print_shop_sku
     *
     * @mbg.generated
     */
    List<LabelPrintShopSku> selectByExample(LabelPrintShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print_shop_sku
     *
     * @mbg.generated
     */
    LabelPrintShopSku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print_shop_sku
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LabelPrintShopSku record, @Param("example") LabelPrintShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print_shop_sku
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LabelPrintShopSku record, @Param("example") LabelPrintShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print_shop_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LabelPrintShopSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_print_shop_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LabelPrintShopSku record);
}