package com.sky.ddt.dao.generate;

import com.sky.ddt.entity.ProduceOrderShopSku;
import com.sky.ddt.entity.ProduceOrderShopSkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProduceOrderShopSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce_order_shop_sku
     *
     * @mbg.generated
     */
    long countByExample(ProduceOrderShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce_order_shop_sku
     *
     * @mbg.generated
     */
    int deleteByExample(ProduceOrderShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce_order_shop_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce_order_shop_sku
     *
     * @mbg.generated
     */
    int insert(ProduceOrderShopSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce_order_shop_sku
     *
     * @mbg.generated
     */
    int insertSelective(ProduceOrderShopSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce_order_shop_sku
     *
     * @mbg.generated
     */
    List<ProduceOrderShopSku> selectByExample(ProduceOrderShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce_order_shop_sku
     *
     * @mbg.generated
     */
    ProduceOrderShopSku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce_order_shop_sku
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProduceOrderShopSku record, @Param("example") ProduceOrderShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce_order_shop_sku
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProduceOrderShopSku record, @Param("example") ProduceOrderShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce_order_shop_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProduceOrderShopSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table produce_order_shop_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProduceOrderShopSku record);
}