package com.sky.ddt.dao.generate;

import com.sky.ddt.entity.StockRecord;
import com.sky.ddt.entity.StockRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated
     */
    long countByExample(StockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated
     */
    int deleteByExample(StockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated
     */
    int insert(StockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated
     */
    int insertSelective(StockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated
     */
    List<StockRecord> selectByExample(StockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated
     */
    StockRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StockRecord record, @Param("example") StockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StockRecord record, @Param("example") StockRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StockRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockRecord record);
}