package com.sky.ddt.dao.generate;

import com.sky.ddt.entity.WarehousingOrderShopSku;
import com.sky.ddt.entity.WarehousingOrderShopSkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WarehousingOrderShopSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order_shop_sku
     *
     * @mbg.generated
     */
    long countByExample(WarehousingOrderShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order_shop_sku
     *
     * @mbg.generated
     */
    int deleteByExample(WarehousingOrderShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order_shop_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order_shop_sku
     *
     * @mbg.generated
     */
    int insert(WarehousingOrderShopSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order_shop_sku
     *
     * @mbg.generated
     */
    int insertSelective(WarehousingOrderShopSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order_shop_sku
     *
     * @mbg.generated
     */
    List<WarehousingOrderShopSku> selectByExample(WarehousingOrderShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order_shop_sku
     *
     * @mbg.generated
     */
    WarehousingOrderShopSku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order_shop_sku
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WarehousingOrderShopSku record, @Param("example") WarehousingOrderShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order_shop_sku
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WarehousingOrderShopSku record, @Param("example") WarehousingOrderShopSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order_shop_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WarehousingOrderShopSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order_shop_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WarehousingOrderShopSku record);
}