package com.sky.ddt.dao.generate;

import com.sky.ddt.entity.WarehousingOrder;
import com.sky.ddt.entity.WarehousingOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WarehousingOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order
     *
     * @mbg.generated
     */
    long countByExample(WarehousingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order
     *
     * @mbg.generated
     */
    int deleteByExample(WarehousingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order
     *
     * @mbg.generated
     */
    int insert(WarehousingOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order
     *
     * @mbg.generated
     */
    int insertSelective(WarehousingOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order
     *
     * @mbg.generated
     */
    List<WarehousingOrder> selectByExample(WarehousingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order
     *
     * @mbg.generated
     */
    WarehousingOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WarehousingOrder record, @Param("example") WarehousingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WarehousingOrder record, @Param("example") WarehousingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WarehousingOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WarehousingOrder record);
}