package com.sky.ddt.entity;

import java.util.Date;

public class LabelPrintShopSku {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_print_shop_sku.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_print_shop_sku.label_print_id
     *
     * @mbg.generated
     */
    private Integer labelPrintId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_print_shop_sku.shop_sku_id
     *
     * @mbg.generated
     */
    private Integer shopSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_print_shop_sku.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_print_shop_sku.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_print_shop_sku.create_by
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_print_shop_sku.id
     *
     * @return the value of label_print_shop_sku.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_print_shop_sku.id
     *
     * @param id the value for label_print_shop_sku.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_print_shop_sku.label_print_id
     *
     * @return the value of label_print_shop_sku.label_print_id
     *
     * @mbg.generated
     */
    public Integer getLabelPrintId() {
        return labelPrintId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_print_shop_sku.label_print_id
     *
     * @param labelPrintId the value for label_print_shop_sku.label_print_id
     *
     * @mbg.generated
     */
    public void setLabelPrintId(Integer labelPrintId) {
        this.labelPrintId = labelPrintId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_print_shop_sku.shop_sku_id
     *
     * @return the value of label_print_shop_sku.shop_sku_id
     *
     * @mbg.generated
     */
    public Integer getShopSkuId() {
        return shopSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_print_shop_sku.shop_sku_id
     *
     * @param shopSkuId the value for label_print_shop_sku.shop_sku_id
     *
     * @mbg.generated
     */
    public void setShopSkuId(Integer shopSkuId) {
        this.shopSkuId = shopSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_print_shop_sku.quantity
     *
     * @return the value of label_print_shop_sku.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_print_shop_sku.quantity
     *
     * @param quantity the value for label_print_shop_sku.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_print_shop_sku.create_time
     *
     * @return the value of label_print_shop_sku.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_print_shop_sku.create_time
     *
     * @param createTime the value for label_print_shop_sku.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_print_shop_sku.create_by
     *
     * @return the value of label_print_shop_sku.create_by
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_print_shop_sku.create_by
     *
     * @param createBy the value for label_print_shop_sku.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }
}