package com.sky.ddt.entity;

import java.util.Date;

public class ProduceOrderShopSku {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce_order_shop_sku.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce_order_shop_sku.produce_order_id
     *
     * @mbg.generated
     */
    private Integer produceOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce_order_shop_sku.shop_sku_id
     *
     * @mbg.generated
     */
    private Integer shopSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce_order_shop_sku.shop_sku
     *
     * @mbg.generated
     */
    private String shopSku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce_order_shop_sku.production_quantity
     *
     * @mbg.generated
     */
    private Integer productionQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce_order_shop_sku.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce_order_shop_sku.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce_order_shop_sku.create_by
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce_order_shop_sku.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column produce_order_shop_sku.update_by
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce_order_shop_sku.id
     *
     * @return the value of produce_order_shop_sku.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce_order_shop_sku.id
     *
     * @param id the value for produce_order_shop_sku.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce_order_shop_sku.produce_order_id
     *
     * @return the value of produce_order_shop_sku.produce_order_id
     *
     * @mbg.generated
     */
    public Integer getProduceOrderId() {
        return produceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce_order_shop_sku.produce_order_id
     *
     * @param produceOrderId the value for produce_order_shop_sku.produce_order_id
     *
     * @mbg.generated
     */
    public void setProduceOrderId(Integer produceOrderId) {
        this.produceOrderId = produceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce_order_shop_sku.shop_sku_id
     *
     * @return the value of produce_order_shop_sku.shop_sku_id
     *
     * @mbg.generated
     */
    public Integer getShopSkuId() {
        return shopSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce_order_shop_sku.shop_sku_id
     *
     * @param shopSkuId the value for produce_order_shop_sku.shop_sku_id
     *
     * @mbg.generated
     */
    public void setShopSkuId(Integer shopSkuId) {
        this.shopSkuId = shopSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce_order_shop_sku.shop_sku
     *
     * @return the value of produce_order_shop_sku.shop_sku
     *
     * @mbg.generated
     */
    public String getShopSku() {
        return shopSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce_order_shop_sku.shop_sku
     *
     * @param shopSku the value for produce_order_shop_sku.shop_sku
     *
     * @mbg.generated
     */
    public void setShopSku(String shopSku) {
        this.shopSku = shopSku == null ? null : shopSku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce_order_shop_sku.production_quantity
     *
     * @return the value of produce_order_shop_sku.production_quantity
     *
     * @mbg.generated
     */
    public Integer getProductionQuantity() {
        return productionQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce_order_shop_sku.production_quantity
     *
     * @param productionQuantity the value for produce_order_shop_sku.production_quantity
     *
     * @mbg.generated
     */
    public void setProductionQuantity(Integer productionQuantity) {
        this.productionQuantity = productionQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce_order_shop_sku.remark
     *
     * @return the value of produce_order_shop_sku.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce_order_shop_sku.remark
     *
     * @param remark the value for produce_order_shop_sku.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce_order_shop_sku.create_time
     *
     * @return the value of produce_order_shop_sku.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce_order_shop_sku.create_time
     *
     * @param createTime the value for produce_order_shop_sku.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce_order_shop_sku.create_by
     *
     * @return the value of produce_order_shop_sku.create_by
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce_order_shop_sku.create_by
     *
     * @param createBy the value for produce_order_shop_sku.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce_order_shop_sku.update_time
     *
     * @return the value of produce_order_shop_sku.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce_order_shop_sku.update_time
     *
     * @param updateTime the value for produce_order_shop_sku.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column produce_order_shop_sku.update_by
     *
     * @return the value of produce_order_shop_sku.update_by
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column produce_order_shop_sku.update_by
     *
     * @param updateBy the value for produce_order_shop_sku.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
}