package com.sky.ddt.entity;

import java.util.Date;

public class WarehousingOrderShopSku {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehousing_order_shop_sku.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehousing_order_shop_sku.warehousing_order_id
     *
     * @mbg.generated
     */
    private Integer warehousingOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehousing_order_shop_sku.shop_sku_id
     *
     * @mbg.generated
     */
    private Integer shopSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehousing_order_shop_sku.shop_sku
     *
     * @mbg.generated
     */
    private String shopSku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehousing_order_shop_sku.warehousing_quantity
     *
     * @mbg.generated
     */
    private Integer warehousingQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehousing_order_shop_sku.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehousing_order_shop_sku.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehousing_order_shop_sku.create_by
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehousing_order_shop_sku.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehousing_order_shop_sku.update_by
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehousing_order_shop_sku.id
     *
     * @return the value of warehousing_order_shop_sku.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehousing_order_shop_sku.id
     *
     * @param id the value for warehousing_order_shop_sku.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehousing_order_shop_sku.warehousing_order_id
     *
     * @return the value of warehousing_order_shop_sku.warehousing_order_id
     *
     * @mbg.generated
     */
    public Integer getWarehousingOrderId() {
        return warehousingOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehousing_order_shop_sku.warehousing_order_id
     *
     * @param warehousingOrderId the value for warehousing_order_shop_sku.warehousing_order_id
     *
     * @mbg.generated
     */
    public void setWarehousingOrderId(Integer warehousingOrderId) {
        this.warehousingOrderId = warehousingOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehousing_order_shop_sku.shop_sku_id
     *
     * @return the value of warehousing_order_shop_sku.shop_sku_id
     *
     * @mbg.generated
     */
    public Integer getShopSkuId() {
        return shopSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehousing_order_shop_sku.shop_sku_id
     *
     * @param shopSkuId the value for warehousing_order_shop_sku.shop_sku_id
     *
     * @mbg.generated
     */
    public void setShopSkuId(Integer shopSkuId) {
        this.shopSkuId = shopSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehousing_order_shop_sku.shop_sku
     *
     * @return the value of warehousing_order_shop_sku.shop_sku
     *
     * @mbg.generated
     */
    public String getShopSku() {
        return shopSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehousing_order_shop_sku.shop_sku
     *
     * @param shopSku the value for warehousing_order_shop_sku.shop_sku
     *
     * @mbg.generated
     */
    public void setShopSku(String shopSku) {
        this.shopSku = shopSku == null ? null : shopSku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehousing_order_shop_sku.warehousing_quantity
     *
     * @return the value of warehousing_order_shop_sku.warehousing_quantity
     *
     * @mbg.generated
     */
    public Integer getWarehousingQuantity() {
        return warehousingQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehousing_order_shop_sku.warehousing_quantity
     *
     * @param warehousingQuantity the value for warehousing_order_shop_sku.warehousing_quantity
     *
     * @mbg.generated
     */
    public void setWarehousingQuantity(Integer warehousingQuantity) {
        this.warehousingQuantity = warehousingQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehousing_order_shop_sku.remark
     *
     * @return the value of warehousing_order_shop_sku.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehousing_order_shop_sku.remark
     *
     * @param remark the value for warehousing_order_shop_sku.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehousing_order_shop_sku.create_time
     *
     * @return the value of warehousing_order_shop_sku.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehousing_order_shop_sku.create_time
     *
     * @param createTime the value for warehousing_order_shop_sku.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehousing_order_shop_sku.create_by
     *
     * @return the value of warehousing_order_shop_sku.create_by
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehousing_order_shop_sku.create_by
     *
     * @param createBy the value for warehousing_order_shop_sku.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehousing_order_shop_sku.update_time
     *
     * @return the value of warehousing_order_shop_sku.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehousing_order_shop_sku.update_time
     *
     * @param updateTime the value for warehousing_order_shop_sku.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehousing_order_shop_sku.update_by
     *
     * @return the value of warehousing_order_shop_sku.update_by
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehousing_order_shop_sku.update_by
     *
     * @param updateBy the value for warehousing_order_shop_sku.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
}